In [1]:
conda install numpy

Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0





Solving environment: ...working... done

## Package Plan ##

  environment location: D:\Anaconda

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2023.12.12 |       haa95532_0         127 KB
    certifi-2023.11.17         |  py311haa95532_0         160 KB
    openssl-3.0.12             |       h2bbff1b_0         7.4 MB
    ------------------------------------------------------------
                                           Total:         7.7 MB

The following packages will be UPDATED:

  ca-certificates                     2023.08.22-haa95532_0 --> 2023.12.12-haa95532_0 
  certifi                         2023.7.22-py311haa95532_0 --> 2023.11.17-py311haa95532_0 
  openssl                                 3.0.10-h2bbff1b_2 --> 3.0.12-h2bbff1b_0 




ca-certificates-2023 | 127 KB    |            |   0% 

certifi-2023.11.17   | 160 KB 

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
#numpy array/diziler

In [6]:
my_List=[10,20,30,40]

In [7]:
type(my_List)

list

In [8]:
np.array(my_List)

array([10, 20, 30, 40])

In [10]:
my_numpy_array=np.array(my_List)

In [11]:
my_numpy_array

array([10, 20, 30, 40])

In [12]:
my_numpy_array[0]

10

In [13]:
my_numpy_array[0]=100

In [14]:
my_numpy_array[0]

100

In [15]:
my_numpy_array.max()

100

In [16]:
my_numpy_array.min()

20

In [17]:
print(my_numpy_array.max)

<built-in method max of numpy.ndarray object at 0x0000022A413CCD50>


In [18]:
print(my_numpy_array)

[100  20  30  40]


In [19]:
print(my_numpy_array.max)

<built-in method max of numpy.ndarray object at 0x0000022A413CCD50>


In [20]:
print(my_numpy_array.max())

100


In [21]:
print(my_numpy_array.min())

20


In [22]:
my_numpy_array.min() / my_numpy_array.max()

0.2

In [23]:
matrix_list=[[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [24]:
type(matrix_list)

list

In [25]:
matrix_list[0]

[1, 0, 0]

In [26]:
matrix_list[0][0]

1

In [27]:
matrix_list[3][0]

0

In [28]:
matrix_list[1][1]

1

In [30]:
numpy_matrix_list=np.array(matrix_list)

In [31]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [32]:
numpy_matrix_list[0]

array([1, 0, 0])

In [33]:
numpy_matrix_list.shape


(4, 3)

In [34]:
#arange

In [35]:
range(0,10)

range(0, 10)

In [36]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
my_range_list=list(range(0,100))

In [38]:
my_range_list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [39]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [42]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [44]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [49]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [50]:
np.random.randint(1,10)

3

In [51]:
np.random.randint(1,10,5)

array([8, 7, 4, 5, 9])

In [52]:
my_numpy_list=np.arange(0,20)

In [53]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [54]:
my_numpy_list[4]

4

In [55]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [56]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [57]:
my_list=list(range(0,20))

In [58]:
my_List

[10, 20, 30, 40]

In [59]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [61]:
my_numpy_list[4:9]=-10

In [62]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [63]:
other_list=np.arange(0,15)

In [64]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [66]:
slicing_list=other_list[4:10]

In [67]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [68]:
slicing_list[:]=100

In [69]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [70]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [71]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [72]:
numpy_list_3=np.arange(0,20)

In [73]:
numpy_list_3_copy=numpy_list_3.copy()

In [74]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [75]:
#numpy operations with numpy arrays

In [76]:
new_array=np.random.randint(1,150,25)

In [77]:
new_array

array([ 29,  66,  17, 104, 133,  23,  26, 136,  41,   4, 147,  10,  83,
         3,  86,  84,  58, 115,  39,   9,  14,  35, 104,  85, 141])

In [78]:
new_array>50

array([False,  True, False,  True,  True, False, False,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True])

In [79]:
result_array=new_array >50

In [80]:
result_array

array([False,  True, False,  True,  True, False, False,  True, False,
       False,  True, False,  True, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True])

In [81]:
new_array[result_array]

array([ 66, 104, 133, 136, 147,  83,  86,  84,  58, 115, 104,  85, 141])

In [82]:
new_array.mean()

63.68

In [83]:
new_array.argmin()

13

In [84]:
last_array=np.arange(0,30)

In [85]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
last_array *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [87]:
last_array**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [88]:
np.min(last_array)

0

In [89]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])

In [94]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [95]:
np.power(last_array,2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841], dtype=int32)

In [96]:
dizi=[0,1,2,3,4,5,6,7,8,9]

In [97]:
dizi

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [98]:
np.power(dizi,3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [99]:
dizi.power()

AttributeError: 'list' object has no attribute 'power'

In [100]:
dizi.power(2)

AttributeError: 'list' object has no attribute 'power'

In [101]:
dizi1=np.arange(10)

In [102]:
dizi1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
dizi1.power()

AttributeError: 'numpy.ndarray' object has no attribute 'power'

In [104]:
dizi1.squeeze()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.power(dizi1,4)

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)